title: Henry Kan Chen
url: ""
baseurl: ""

markdown: kramdown
#ins_logo: "./bits-logo.png"

tracking_id: #

footer: yes
footer_url: "https://www.linkedin.com/in/henry-chen-b1417114"
footer_text: "Page created by Henry Kan Chen"

sass:
    style: compressed
    sass_dir: _sass

nav:
 - name: "About"
   link: ""
 - name: "Resume"
   link: "resume.pdf"
 - name: "Contact"
   link: "contact"
